version: '3.2'
services: 
  db:
    container_name: db
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bluprints@2021"
    image: microsoft/mssql-server-linux:2017-latest
    ports: 
      - "1433:1433"
    restart: on-failure
    volumes:
      - ./volumes/mssql/data:/var/opt/mssql/data
      - ./volumes/mssql/logs:/var/opt/mssql/log
      - ./volumes/mssql/secrets:/var/opt/mssql/secrets